// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlHcrLuQ0dJD-Ny24CpeM1HQO6inMxjkE',
    appId: '1:267181739561:web:8b1700ce6a58922038d638',
    messagingSenderId: '267181739561',
    projectId: 'flash-chat-flutter-af9e0',
    authDomain: 'flash-chat-flutter-af9e0.firebaseapp.com',
    storageBucket: 'flash-chat-flutter-af9e0.appspot.com',
    measurementId: 'G-TWEXF5GJYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiJBkCPJ3Jd8yTfR2Q7gx2eS3ydkBZ91g',
    appId: '1:267181739561:android:9cbeefcfc44d80c838d638',
    messagingSenderId: '267181739561',
    projectId: 'flash-chat-flutter-af9e0',
    storageBucket: 'flash-chat-flutter-af9e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvnWyG_g4l4_Jrj6VxqpCfLIdP-u41bqo',
    appId: '1:267181739561:ios:bdbd224135a874fd38d638',
    messagingSenderId: '267181739561',
    projectId: 'flash-chat-flutter-af9e0',
    storageBucket: 'flash-chat-flutter-af9e0.appspot.com',
    iosBundleId: 'com.example.flashChatFlutte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvnWyG_g4l4_Jrj6VxqpCfLIdP-u41bqo',
    appId: '1:267181739561:ios:bdbd224135a874fd38d638',
    messagingSenderId: '267181739561',
    projectId: 'flash-chat-flutter-af9e0',
    storageBucket: 'flash-chat-flutter-af9e0.appspot.com',
    iosBundleId: 'com.example.flashChatFlutte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlHcrLuQ0dJD-Ny24CpeM1HQO6inMxjkE',
    appId: '1:267181739561:web:7cf48b657985772038d638',
    messagingSenderId: '267181739561',
    projectId: 'flash-chat-flutter-af9e0',
    authDomain: 'flash-chat-flutter-af9e0.firebaseapp.com',
    storageBucket: 'flash-chat-flutter-af9e0.appspot.com',
    measurementId: 'G-BVT6MFXX56',
  );
}
